name: Build NextJS Docker Image

on:
  workflow_dispatch:  # Enables manual triggers
  push:
    branches: [ main ]
    paths:
      - 'src/AINarrativePainting.NextJS/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/AINarrativePainting.NextJS/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src/AINarrativePainting.NextJS
        file: ./src/AINarrativePainting.NextJS/Dockerfile
        push: false
        tags: ainarrativepainting-nextjs:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    
    # Temp fix for cache handling
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache