name: Build NextJS Docker Image

on:
  workflow_dispatch:  # Enables manual triggers
  push:
    tags:
      - "v-api-*"

# Add permissions block
permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Get version
      id: get_version
      run: |
        # Strip v prefix: v-api-1.0.1 -> 1.0.1
        VERSION=${GITHUB_REF#refs/tags/v-api-}
        # Convert to build number: 1.0.1 -> 1000001
        BUILD_VERSION=$(echo $VERSION | sed -e 's/\./ /g' | xargs printf "%d%03d%03d")
        # Keep original tag: v1.0.1
        DISPLAY_VERSION=${GITHUB_REF#refs/tags/}

        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_OUTPUT
        echo "DISPLAY_VERSION=$DISPLAY_VERSION" >> $GITHUB_OUTPUT


    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .env.prod
      run: |
        cat > ./src/AINarrativePainting.NextJS/.env.prod << EOL
        Dify_API_URL=${{ secrets.Dify_API_URL }}
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        ImgProxyUrl=${{ secrets.ImgProxyUrl }}
        COS_SecretId=${{ secrets.COS_SecretId }}
        COS_SecretKey=${{ secrets.COS_SecretKey }}
        COS_Region=${{ secrets.COS_Region }}
        COS_Bucket=${{ secrets.COS_Bucket }}
        EOL
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src/AINarrativePainting.NextJS
        file: ./src/AINarrativePainting.NextJS/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/ainarrativepainting-nextjs:${{ steps.get_version.outputs.VERSION }}
          ghcr.io/${{ github.repository_owner }}/ainarrativepainting-nextjs:latest
          ghcr.io/${{ github.repository_owner }}/ainarrativepainting-nextjs:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
    
    # Temp fix for cache handling
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache