name: Publish MAUI iOS App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # build workspace ./src/AINarrativePainting.React
      - name: Install dependencies
        run: |
          npm install
          npm run build
        working-directory: src/AINarrativePainting.React

      # copy dist to artifact
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: react-build
          path: src/AINarrativePainting.React/dist

  build-ios:
    runs-on: macos-latest
    steps:
      # copy react build to maui project
      - name: Checkout code
        uses: actions/checkout@v3

      # download artifact from previous step and copy to maui project
      - uses: actions/download-artifact@v3.0.0
        with:
          name: react-build
          path: src/AINarrativePainting.App/Resources/Raw/wwwroot

      - name: list files
        run: |
          ls -la src/AINarrativePainting.App/Resources/Raw/wwwroot

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install MAUI Workload
        run: |
          dotnet workload install maui
          dotnet workload install ios

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install Provisioning Profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: "art.aishuohua.app"
          # profile-type: "IOS_APP_STORE"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Build MAUI iOS
        run: |
          dotnet publish  src/AINarrativePainting.App/AINarrativePainting.App.csproj \
           -f net9.0-ios -c Release \
          /p:ArchiveOnBuild=true \
          /p:RuntimeIdentifier=ios-arm64 \
          /p:CodesignKey="${{ secrets.APPLE_SIGNING_IDENTITY }}" \
          /p:CodesignProvision="${{ secrets.APPLE_PROVISIONING_PROFILE_NAME }}"

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "src/AINarrativePainting.App/bin/Release/net9.0-ios/ios-arm64/publish/AINarrativePainting.App.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: "src/AINarrativePainting.App/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa"
